/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab01.Interfaces;

import java.text.SimpleDateFormat;
import lab01.Handlers.Fabrica;
import lab01.Clases.DataCliente;
import lab01.Clases.Cliente;
import java.util.Date;
import lab01.Clases.DataRestaurante;

/**
 *
 * @author martin
 */
public class CargarDatos extends javax.swing.JFrame {
    private ICtrlUsuario ICU;
    private ICtrlPedido ICPed;
    private ICtrlProducto ICProd;
    /**
     * Creates new form CargarDatos
     */
    public CargarDatos() {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        ICU = fabrica.getICtrlUsuario();
        ICPed = fabrica.getICtrlPedido();
        ICProd = fabrica.getICtrlProducto();     
        CrearDatosPorDefecto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void CrearDatosPorDefecto(){

      //CLIENTES
      
      ICU.ingresarDatos("costas", "gcostas@gmail.com","Gerardo",  "Av. Italia 2078");
      ICU.registrarCliente("Costas", "/home/martin/NetBeansProjects/ProgAplicaciones/images/costas.jpeg", "15/11/1983");
      
      ICU.ingresarDatos("roro", "rcotelo@yahoo.com","Rodrigo", "Pdte. Berro 1548");
      ICU.registrarCliente("Cotelo", "/home/martin/NetBeansProjects/ProgAplicaciones/images/roro.jpeg", "02/08/1975");

      ICU.ingresarDatos("chechi", "cgarrido@hotmail.com","Cecilia", "Gral. Urquiza 1548");
      ICU.registrarCliente("Garrido", "/home/martin/NetBeansProjects/ProgAplicaciones/images/chechi.jpeg", "12/09/1987");
      
      ICU.ingresarDatos("andy", "agarcia@gmail.com","Andrea", "Dr. Manuel Albo 4512");
      ICU.registrarCliente("García", "/home/martin/NetBeansProjects/ProgAplicaciones/images/andy.jpeg", "28/07/1951");

      ICU.ingresarDatos("weiss", "aweiss@gmail.com","Adrián", "Monte Caseros 5615");
      ICU.registrarCliente("Weiss", "/home/martin/NetBeansProjects/ProgAplicaciones/images/generico.jpeg", "23/12/1978");
  
      //CATEGORÍAS
      
      //RESTAURANTES
      
      ICU.ingresarDatos("mera", "mera@hotmail.com", "Pizzería Mera", "Av 8 de octubre 2704");
      DataRestaurante res1 = new DataRestaurante("mera", "Pizzeria Mera", "mera@hotmail.com", "Av 8 de octubre 2704", null, null);
      ICU.registrarRestaurante(res1);
      
      ICU.ingresarDatos("rossell", "bar.rossel@gmail.com", "Bar Rossell", "Bvar. Artigas 1601");
      DataRestaurante res2 = new DataRestaurante("rossell", "Bar Rossell", "bar.rossel@gmail.com", "Bvar. Artigas 1601", null, null);
      ICU.registrarRestaurante(res2);
 
      ICU.ingresarDatos("bocatti", "bocatti@gmail.com", "Empanadas Bocatti", "18 de julio 2138");
      DataRestaurante res3 = new DataRestaurante("bocatti", "Empanadas Bocatti", "bocatti@gmail.com", "18 de julio 2138", null, null);
      ICU.registrarRestaurante(res3);  
      
      ICU.ingresarDatos("winb", "wok.in.box@hotmail.com", "Wok in Box", "Libertad 2535");
      DataRestaurante res4 = new DataRestaurante("winb", "Wok in Box", "wok.in.box@hotmail.com", "Libertad 2535", null, null);
      ICU.registrarRestaurante(res4); 
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
