/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab01.Interfaces;

import java.text.SimpleDateFormat;
import lab01.Handlers.Fabrica;
import lab01.Clases.DataCliente;
import lab01.Clases.Cliente;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import lab01.Clases.DataRestaurante;

/**
 *
 * @author martin
 */
public class CargarDatos extends javax.swing.JFrame {
    private ICtrlUsuario ICU;
    private ICtrlPedido ICPed;
    private ICtrlProducto ICProd;
    /**
     * Creates new form CargarDatos
     */
    public CargarDatos() {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        ICU = fabrica.getICtrlUsuario();
        ICPed = fabrica.getICtrlPedido();
        ICProd = fabrica.getICtrlProducto();     
        CrearDatosPorDefecto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void CrearDatosPorDefecto(){

      //CLIENTES
      
      ICU.ingresarDatos("costas", "gcostas@gmail.com","Gerardo",  "Av. Italia 2078");
      ICU.registrarCliente("Costas", "/home/martin/NetBeansProjects/ProgAplicaciones/images/costas.jpeg", "15/11/1983");
      
      ICU.ingresarDatos("roro", "rcotelo@yahoo.com","Rodrigo", "Pdte. Berro 1548");
      ICU.registrarCliente("Cotelo", "/home/martin/NetBeansProjects/ProgAplicaciones/images/roro.jpeg", "02/08/1975");

      ICU.ingresarDatos("chechi", "cgarrido@hotmail.com","Cecilia", "Gral. Urquiza 1548");
      ICU.registrarCliente("Garrido", "/home/martin/NetBeansProjects/ProgAplicaciones/images/chechi.jpeg", "12/09/1987");
      
      ICU.ingresarDatos("andy", "agarcia@gmail.com","Andrea", "Dr. Manuel Albo 4512");
      ICU.registrarCliente("García", "/home/martin/NetBeansProjects/ProgAplicaciones/images/andy.jpeg", "28/07/1951");

      ICU.ingresarDatos("weiss", "aweiss@gmail.com","Adrián", "Monte Caseros 5615");
      ICU.registrarCliente("Weiss", "/home/martin/NetBeansProjects/ProgAplicaciones/images/generico.jpeg", "23/12/1978");
  
      //CATEGORÍAS
      
      ICU.registrarCat("Chivitos");
      ICU.registrarCat("Minutas");
      ICU.registrarCat("Parrilla");
      ICU.registrarCat("Pizzas");
      ICU.registrarCat("Empanadas");
      ICU.registrarCat("Milanesas");
      ICU.registrarCat("Ensaladas");
      ICU.registrarCat("Pastas");
      ICU.registrarCat("Comida China");
      ICU.registrarCat("Picadas");
      ICU.registrarCat("Woks");
      ICU.registrarCat("Comida Mexicana");
      ICU.registrarCat("Entradas");
      ICU.registrarCat("Bebidas");
      ICU.registrarCat("Sushi");
      
      //RESTAURANTES
      
      ICU.ingresarDatos("mera", "mera@hotmail.com", "Pizzería Mera", "Av 8 de octubre 2704");

      
      Map Categorias1 = new HashMap();
      Categorias1.put("Chivitos", ICU.retColCat().get("Chivitos"));
      Categorias1.put("Minutas", ICU.retColCat().get("Minutas"));
      Categorias1.put("Parrilla", ICU.retColCat().get("Parrilla"));
      Categorias1.put("Pizzas", ICU.retColCat().get("Pizzas"));
      DataRestaurante res1 = new DataRestaurante();
      res1.setColCategoria(Categorias1);
      res1.setColProducto(null);
      res1.setDireccion("Av 8 de octubre 2704");
      res1.setEmail("mera@hotmail.com");
      res1.setLstImagen(null);
      res1.setNickname("mera");
      res1.setNombre("Pizzería Mera");
      ICU.registrarRestaurante(res1);
      
      Map Categorias2 = new HashMap();
      Categorias2.put("Chivitos", ICU.retColCat().get("Chivitos"));
      Categorias2.put("Minutas", ICU.retColCat().get("Minutas"));
      Categorias2.put("Pastas", ICU.retColCat().get("Pastas"));
      Categorias2.put("Pizzas", ICU.retColCat().get("Pizzas"));
      DataRestaurante res2 = new DataRestaurante();
      res2.setColCategoria(Categorias2);
      res2.setColProducto(null);
      res2.setDireccion("Bvar. Artigas 1601");
      res2.setEmail("bar.rossel@gmail.com");
      res2.setLstImagen(null);
      res2.setNickname("rossell");
      res2.setNombre("Bar Rossell");
      ICU.registrarRestaurante(res2);
      
      Map Categorias3 = new HashMap();
      Categorias3.put("Empanadas", ICU.retColCat().get("Empanadas"));
      DataRestaurante res3 = new DataRestaurante();
      res3.setColCategoria(Categorias3);
      res3.setColProducto(null);
      res3.setDireccion("18 de julio 2138");
      res3.setEmail("bocatti@gmail.com");
      res3.setLstImagen(null);
      res3.setNickname("bocatti");
      res3.setNombre("Empanadas Bocatti");
      ICU.registrarRestaurante(res3);
      
      Map Categorias4 = new HashMap();
      Categorias4.put("Woks", ICU.retColCat().get("Woks"));
      Categorias4.put("Pastas", ICU.retColCat().get("Pastas"));
      Categorias4.put("Comida China", ICU.retColCat().get("Comida China"));
      DataRestaurante res4 = new DataRestaurante();
      res4.setColCategoria(Categorias4);
      res4.setColProducto(null);
      res4.setDireccion("Libertad 2535");
      res4.setEmail("wok.in.box@hotmail.com");
      res4.setLstImagen(null);
      res4.setNickname("winb");
      res4.setNombre("Wok in Box");
      ICU.registrarRestaurante(res4);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
