/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab01.Interfaces;

import java.util.Iterator;
import java.util.Map;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import lab01.Clases.DataCliente;
import lab01.Handlers.Fabrica;

/**
 *
 * @author joaquin
 */
public class ElegirProductos extends javax.swing.JInternalFrame {

    private String rest;
    private ICtrlUsuario ICU;
    DefaultTableModel modelo;
    private ICtrlProducto CP;
    /**
     * Creates new form EjegirProductos
     */
    public ElegirProductos(String r) {
        initComponents();
        rest=r;
        Fabrica fabrica = Fabrica.getInstance();
        ICU = fabrica.getICtrlUsuario();
        CP = fabrica.getICtrlProducto();
        modelo = (DefaultTableModel)jTabla.getModel();
        cargarTabla();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jblisto = new javax.swing.JButton();

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Individual", "En Stock", "Select Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabla);

        jblisto.setText("Listo");
        jblisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblistoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblisto)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jblisto)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblistoActionPerformed
        // TODO add your handling code here:
        Map prodPromo = new HashMap();
        for(int i=0; i<jTabla.getRowCount(); i++){
            if(!modelo.getValueAt(i,2).toString().equals("0")){
            String nom = modelo.getValueAt(i,0).toString();
            String cant = modelo.getValueAt(i,2).toString();
            prodPromo.put(nom, cant);}
        }
    CP.setPromo(prodPromo);
    this.dispose();
    }//GEN-LAST:event_jblistoActionPerformed

    
    public void cargarTabla(){
    Map prods; 
        prods=ICU.listaProductosStock(rest);
        Iterator it = prods.entrySet().iterator();
        String lista[]=new String[3];
        while(it.hasNext()){
            Map.Entry map = (Map.Entry) it.next();
            String nomprod = (String) map.getKey();
            String cant = (String)map.getValue().toString();
            //lista[0]=model.getSize()-1;
            lista[0]=nomprod;
            lista[1]=cant;
            lista[2]="0";
            modelo.insertRow((int)jTabla.getRowCount(), lista);
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JButton jblisto;
    // End of variables declaration//GEN-END:variables
}
