/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab01.Interfaces;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lab01.Clases.Restaurante;
import lab01.Handlers.Fabrica;

/**
 *
 * @author gera
 */
public class ListarProductosRestaurante extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarProductosRestaurante
     */
    ICtrlUsuario ICU;
    ICtrlPedido ICP;
    int fila = 0;
    public ListarProductosRestaurante(String res) {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        ICU = fabrica.getICtrlUsuario();
        modelo = (DefaultTableModel)tblProductosRes.getModel();
        ICP = fabrica.getICtrlPedido();
        LoadTableProductRest(res);
    }
    DefaultTableModel modelo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductosRes = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblProductosRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Productos", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductosRes);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAgregar)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int j = tblProductosRes.getRowCount();
        for(int i=0; i<tblProductosRes.getRowCount(); i++){
            if(!modelo.getValueAt(i,1).toString().equals("0")){
                String nom = modelo.getValueAt(i,0).toString();
                int cant = (int)modelo.getValueAt(i,1);
               // try{
                    ICP.selectProductos(nom, cant);
                //}catch (Exception ex){
                    
                //}
                
            }
        }
        this.dispose();
        ICP.setDp(ICP.altaPedido());
        AltaPedido ap = new AltaPedido();
        Console.EscritorioMenu.add(ap);
        ap.show();
        
    }//GEN-LAST:event_btnAgregarActionPerformed
    
    private void LoadTableProductRest(String res){
        Restaurante r = null;
        String lista[]=new String[2];
        r = ICU.getRestauranteByNickname(res);
        ICP.setMemRestaurante(res);
        Map lstProd = r.obtenerListaProductos();
        Iterator it = lstProd.entrySet().iterator();
        while(it.hasNext()){
            Map.Entry mapcol = (Map.Entry) it.next();
            String nomProd = mapcol.getKey().toString();
            lista[0]=nomProd;
            lista[1]= "0";
            modelo.insertRow((int)fila, lista);
            fila++;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductosRes;
    // End of variables declaration//GEN-END:variables
}
