/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab01.Interfaces;

import java.awt.Point;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import lab01.Handlers.Fabrica;
import javax.swing.table.DefaultTableModel;
import lab01.Clases.DataPedido;
import lab01.Clases.DataProducto;
import lab01.Clases.DataRestaurante;
import lab01.Clases.Pedido;
import lab01.Clases.Producto;
import lab01.Clases.Producto_Stock;
import lab01.Clases.estados;
import lab01.Handlers.HUsuario;


/**
 *
 * @author joaquin
 */
public class ListarPedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarPedidos
     */
    DefaultTableModel model;
    ICtrlPedido ICP;
    Pedido ped;
    private Map listaPedidos;
    
    public ListarPedidos() {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        ICP = fabrica.getICtrlPedido();
        model = (DefaultTableModel)jTabla.getModel();
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabla.setName("Pedidos"); // NOI18N
        jTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaMouseClicked
        // TODO add your handling code here:
        String idPedido = null;
        long id = 0;
        listaPedidos = ICP.listDataPedidos();
        JTable tab = (JTable)evt.getSource();
        Point point = evt.getPoint();
        int fila = tab.rowAtPoint(point);
        if(evt.getClickCount() == 1){
            idPedido = jTabla.getValueAt(fila,0).toString();
            id = Long.parseLong(idPedido);
        }
//        try{
            Pedido ped = (Pedido)listaPedidos.get(id);
             
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, "El pedido no esta en el sistema","Error",JOptionPane.ERROR_MESSAGE);
//        }
         
        InfoPedidoYBaja infoPed = new InfoPedidoYBaja(ped);
        infoPed.setVisible(true);
    }//GEN-LAST:event_jTablaMouseClicked
    
    public void CargarTabla(){
        Map lp =ICP.listDataPedidos();
        Iterator it = lp.entrySet().iterator();
        String lista[]=new String[1];
            while(it.hasNext()){
                Map.Entry map = (Map.Entry) it.next();
                Pedido ped = (Pedido)map.getValue();
                String id = String.valueOf(ped.getId());
                lista[0]=id;
                model.insertRow((int)jTabla.getRowCount(), lista);
                
            }
                        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
}
