/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab01.Interfaces;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import lab01.Handlers.Fabrica;
import javax.swing.table.DefaultTableModel;
import lab01.Clases.DataPedido;
import lab01.Clases.DataProducto;
import lab01.Clases.DataRestaurante;
import lab01.Clases.Pedido;
import lab01.Clases.Producto;
import lab01.Clases.Producto_Stock;
import lab01.Clases.estados;
import lab01.Handlers.HUsuario;


/**
 *
 * @author joaquin
 */
public class ListarPedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarPedidos
     */
    DefaultTableModel model;
    ICtrlUsuario ICU;
    ICtrlPedido ICP;
    DataPedido ped;
    private Map listaProductos;
    
    public ListarPedidos() {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        ICU = fabrica.getICtrlUsuario();
        model = (DefaultTableModel)jTabla.getModel();
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabla.setName("Pedidos"); // NOI18N
        jTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaMouseClicked
//        // TODO add your handling code here:
////        int idPedido = 0;
////        idPedido = Integer.parseInt(evt.toString());
//        
//        listaProductos = ped.getColCarrito();
//        Iterator it = listaProductos.entrySet().iterator();
//        Producto_Stock p;
//        Producto prod;
//       
//        int i =0;
//        int max = listaProductos.size();
//        while(it.hasNext()){
//            Map.Entry map = (Map.Entry) it.next();
//            p = map.getValue();
//            //dp = ge
//            prod = p.getProd();
//            VerInfoProd verinfo = new VerInfoProd(prod);
//            verinfo.setVisible(true);
//        }
//    }                                   
//            prod = p.getProd();
//            VerInfoProd verinfo = new VerInfoProd(prod);
//            verinfo.setVisible(true);
//        }
    }//GEN-LAST:event_jTablaMouseClicked
    public void CargarTabla(){
        Map lp =ICU.listarPedidos();
        Iterator it = lp.entrySet().iterator();
        String lista[]=new String[1];
            while(it.hasNext()){
                Map.Entry map = (Map.Entry) it.next();
                String id = map.getKey().toString();
                ped = (DataPedido)lp.get(map.getKey());
                lista[0]=id;
                model.insertRow((int)jTabla.getRowCount(), lista);
                
            }
                        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
}
