/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab01.Interfaces;

import java.awt.event.ItemEvent;
import java.util.Map;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;
import lab01.Clases.Cliente;
import lab01.Clases.DataCant_Individual;
import lab01.Clases.DataCliente;
import lab01.Clases.DataIndividual;
import lab01.Clases.DataProducto;
//import lab01.Clases.DataProducto_Stock;
import lab01.Handlers.Fabrica;

/**
 *
 * @author gonzalo
 */
public class RegProducto extends javax.swing.JInternalFrame {

    private ICtrlProducto CP;
    private ICtrlUsuario ICU;

    public RegProducto() {
        initComponents();
        Fabrica f = Fabrica.getInstance();
        CP = f.getICtrlProducto();
        ICU=f.getICtrlUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngProducto = new javax.swing.ButtonGroup();
        jp1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblRest = new javax.swing.JLabel();
        tbNombre = new javax.swing.JTextField();
        tbDesc = new javax.swing.JTextField();
        tbRest = new javax.swing.JTextField();
        rbIndividual = new javax.swing.JRadioButton();
        rbPromocional = new javax.swing.JRadioButton();
        jp2 = new javax.swing.JPanel();
        lblExaminar = new javax.swing.JLabel();
        tbCantidad = new javax.swing.JTextField();
        lblDesc1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de producto"));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        jp1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo producto")));

        lblNombre.setText("Nombre del producto: ");

        lblCantidad.setText("Cantidad: ");

        lblRest.setText("Restaurante: ");

        tbNombre.setEnabled(false);

        tbDesc.setEnabled(false);

        tbRest.setEnabled(false);

        btngProducto.add(rbIndividual);
        rbIndividual.setText("Individual");
        rbIndividual.setEnabled(false);
        rbIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIndividualActionPerformed(evt);
            }
        });

        btngProducto.add(rbPromocional);
        rbPromocional.setText("Promocional");
        rbPromocional.setEnabled(false);
        rbPromocional.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPromocionalItemStateChanged(evt);
            }
        });
        rbPromocional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPromocionalActionPerformed(evt);
            }
        });

        jp2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargar Imagen"));

        lblExaminar.setText("Examinar: ");

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblExaminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblExaminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbCantidad.setEnabled(false);

        lblDesc1.setText("Descripción: ");

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre)
                            .addComponent(lblDesc1)
                            .addComponent(lblCantidad)
                            .addComponent(lblRest))
                        .addGap(18, 18, 18)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(tbDesc))
                            .addComponent(tbRest, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rbIndividual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbPromocional)
                .addGap(126, 126, 126))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(tbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesc1))
                .addGap(18, 18, 18)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRest))
                .addGap(15, 15, 15)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad))
                .addGap(18, 18, 18)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIndividual)
                    .addComponent(rbPromocional))
                .addGap(31, 31, 31)
                .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnRegistro.setText("Registrar");
        btnRegistro.setEnabled(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnRegistro)
                    .addComponent(btnCancel))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        habilitarCampos();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        boolean Promocional = false;
        String p;
        double precio;
        double descuento;
        int cantidad;
        

        if (evt.getSource() == btnRegistro) {
            if (CP.existeRestaurante(tbRest.getText())) { // si el restaurante se encuentra registrado
                if (rbIndividual.isSelected()) { // si quiero registar producto individual
                    p = JOptionPane.showInputDialog(null, "Ingrese el precio", "Ingreso de precio", JOptionPane.INFORMATION_MESSAGE);
                    precio = Double.parseDouble(p);    // ingreso el precio                
                    cantidad = Integer.parseInt(tbCantidad.getText()); // me guardo la cantidad de productos para ese producto particular
                    DataIndividual di = new DataIndividual(tbNombre.getText(), tbDesc.getText(), precio, cantidad); // me guardo los datos en el dataproducto
                    
                   
                    CP.registrarProducto(di, tbRest.getText(), Promocional); // registro producto
                    JOptionPane.showMessageDialog(null, "Producto registrado con exito", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                } else { // si es promocional
                    if (rbPromocional.isSelected()) {
                        /*Iterator it = CP.listarIndividuales(tbRest.getText()).entrySet().iterator();

                        while (it.hasNext()) {
                            Map.Entry map = (Map.Entry) it.next();
                            
                            DataIndividual di = (DataIndividual) map.getValue();
                            JOptionPane.showMessageDialog(null, "Nombre: " + di.getDataNombre() + "cantidad:"+  di.getCantidad(), "aviso", JOptionPane.INFORMATION_MESSAGE);    
                        }*/
                        p = JOptionPane.showInputDialog(null, "Ingrese descuento:", "Ingreso de descuento", JOptionPane.INFORMATION_MESSAGE);
                        descuento = Double.parseDouble(p);
                        CP.armarPromo(tbRest.getText(),tbNombre.getText(),tbDesc.getText(), descuento);
                        JOptionPane.showMessageDialog(null, "Promocion registrada con exito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        
                    }

                }

            } else {
                JOptionPane.showMessageDialog(null, "El restaurante " + tbRest.getText() + " no se encuentra registrado", "Error", JOptionPane.INFORMATION_MESSAGE);
            }

        }


    }//GEN-LAST:event_btnRegistroActionPerformed

    private void rbIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIndividualActionPerformed
        tbCantidad.setEnabled(true);
    }//GEN-LAST:event_rbIndividualActionPerformed

    private void rbPromocionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPromocionalActionPerformed
        tbCantidad.setEnabled(false);
        
    }//GEN-LAST:event_rbPromocionalActionPerformed

    private void rbPromocionalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPromocionalItemStateChanged
// TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED){
            //ICU.setNickname(tbRest.getText());
            ElegirProductos ep = new ElegirProductos(tbRest.getText());
             Console.EscritorioMenu.add(ep);
             ep.show();
        }
           
        
    }//GEN-LAST:event_rbPromocionalItemStateChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    public void habilitarCampos() {
        tbNombre.setEnabled(true);
        tbDesc.setEnabled(true);
        tbRest.setEnabled(true);
        rbIndividual.setEnabled(true);
        rbPromocional.setEnabled(true);
        btnRegistro.setEnabled(true);
        btnCancel.setEnabled(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistro;
    private javax.swing.ButtonGroup btngProducto;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDesc1;
    private javax.swing.JLabel lblExaminar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRest;
    private javax.swing.JRadioButton rbIndividual;
    private javax.swing.JRadioButton rbPromocional;
    private javax.swing.JTextField tbCantidad;
    private javax.swing.JTextField tbDesc;
    private javax.swing.JTextField tbNombre;
    private javax.swing.JTextField tbRest;
    // End of variables declaration//GEN-END:variables
}
