/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab01.Interfaces;

import javax.swing.JOptionPane;
import lab01.Clases.DataProducto;
import lab01.Handlers.Fabrica;

/**
 *
 * @author gonzalo
 */
public class RegProducto extends javax.swing.JInternalFrame {

    private ICtrlProducto CP;

    public RegProducto() {
        initComponents();
        Fabrica f = Fabrica.getInstance();
        CP = f.getICtrlProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngProducto = new javax.swing.ButtonGroup();
        jp1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblRest = new javax.swing.JLabel();
        tbNombre = new javax.swing.JTextField();
        tbDesc = new javax.swing.JTextField();
        tbRest = new javax.swing.JTextField();
        rbIndividual = new javax.swing.JRadioButton();
        rbPromocional = new javax.swing.JRadioButton();
        jp2 = new javax.swing.JPanel();
        lblExaminar = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de producto"));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        jp1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo producto")));

        lblNombre.setText("Nombre del producto: ");

        lblDesc.setText("Descripción: ");

        lblRest.setText("Restaurante: ");

        tbNombre.setEnabled(false);

        tbDesc.setEnabled(false);

        tbRest.setEnabled(false);

        btngProducto.add(rbIndividual);
        rbIndividual.setText("Individual");
        rbIndividual.setEnabled(false);

        btngProducto.add(rbPromocional);
        rbPromocional.setText("Promocional");
        rbPromocional.setEnabled(false);

        jp2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargar Imagen"));

        lblExaminar.setText("Examinar: ");

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblExaminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblExaminar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRest)
                    .addComponent(lblDesc)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addComponent(rbIndividual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPromocional))
                    .addComponent(tbNombre)
                    .addComponent(tbDesc)
                    .addComponent(tbRest))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(jp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(tbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesc)
                    .addComponent(tbDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIndividual)
                    .addComponent(rbPromocional))
                .addGap(33, 33, 33)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRest)
                    .addComponent(tbRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnRegistro.setText("Registrar");
        btnRegistro.setEnabled(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnRegistro)
                    .addComponent(btnCancel))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        habilitarCampos();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        boolean Promocional = false;
        String p;
        double precio;

        if (evt.getSource() == btnRegistro) {
            if (CP.existeRestaurante(tbRest.getText())) {
                if (rbIndividual.isSelected()) {
                    p = JOptionPane.showInputDialog(null, "Ingrese el precio", "Ingreso de precio", JOptionPane.INFORMATION_MESSAGE);
                    precio = Double.parseDouble(p);
                    DataProducto dp = new DataProducto(tbNombre.getText(), tbDesc.getText(), precio);                  
                    CP.registrarProducto(dp, tbRest.getText(), Promocional);
                    JOptionPane.showMessageDialog(null, "Producto registrado con exito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }

            } else {
                 JOptionPane.showMessageDialog(null, "El restaurante " + tbRest.getText() + "no se encuentra registrado", "Error", JOptionPane.INFORMATION_MESSAGE);
            }

        }


    }//GEN-LAST:event_btnRegistroActionPerformed

    public void habilitarCampos() {
        tbNombre.setEnabled(true);
        tbDesc.setEnabled(true);
        tbRest.setEnabled(true);
        rbIndividual.setEnabled(true);
        rbPromocional.setEnabled(true);
        btnRegistro.setEnabled(true);
        btnCancel.setEnabled(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistro;
    private javax.swing.ButtonGroup btngProducto;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblExaminar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRest;
    private javax.swing.JRadioButton rbIndividual;
    private javax.swing.JRadioButton rbPromocional;
    private javax.swing.JTextField tbDesc;
    private javax.swing.JTextField tbNombre;
    private javax.swing.JTextField tbRest;
    // End of variables declaration//GEN-END:variables
}
