/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab01.Interfaces;

import java.awt.event.ItemEvent;
import lab01.Handlers.Fabrica;
import java.util.Map;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author joaquin
 */
public class SeleccionarCat extends javax.swing.JInternalFrame {
    private ICtrlUsuario ICU;

    /**
     * Creates new form SeleccionarCat
     */
    public SeleccionarCat() {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        ICU = fabrica.getICtrlUsuario();
        this.cargarCBbox();
        model = new DefaultListModel();
    }
    DefaultListModel model;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbSelect = new javax.swing.JComboBox();
        jbSelect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList();

        jcbSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select..." }));
        jcbSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbSelectItemStateChanged(evt);
            }
        });
        jcbSelect.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jcbSelectMouseDragged(evt);
            }
        });

        jbSelect.setText(">");
        jbSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelectActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbSelect))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelectActionPerformed
        //jLista.setModel(model);

// TODO add your handling code here:
    }//GEN-LAST:event_jbSelectActionPerformed

    private void jcbSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbSelectItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED)
            model.addElement(evt.getItem().toString());
        jLista.setModel(model);
        

//String s = (String) jcbSelect.getSelectedItem();
// TODO add your handling code here:
    }//GEN-LAST:event_jcbSelectItemStateChanged

    private void jcbSelectMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbSelectMouseDragged




// TODO add your handling code here:
    }//GEN-LAST:event_jcbSelectMouseDragged
    public void cargarCBbox(){
        Map cats; 
        cats=ICU.retColCat();
        Iterator it = cats.entrySet().iterator();
        while(it.hasNext()){
            Map.Entry map = (Map.Entry) it.next();
            jcbSelect.addItem(map.getKey().toString());
        }
    
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSelect;
    private javax.swing.JComboBox jcbSelect;
    // End of variables declaration//GEN-END:variables
}
