/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab01.Interfaces;
import java.awt.Point;
import lab01.Clases.DataProducto;
import lab01.Clases.DataRestaurante;
import lab01.Handlers.Fabrica;
import java.util.Map;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import lab01.Clases.DataCliente;
import lab01.Clases.Producto;
import lab01.Interfaces.VerInfoProducto_old;
import lab01.Clases.Restaurante;


/**
 *
 * @author martin
 */
public class VerProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerProducto
     */
    ICtrlUsuario ICU;
    public VerProducto() {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        ICU = fabrica.getICtrlUsuario();
        modelo = (DefaultTableModel)jTabla.getModel();
        cargarTabla();
    }
    DefaultTableModel modelo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", ""},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Restaurante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaMousePressed
        // TODO add your handling code here:
        String nick = null;
        String nomProd = null;
        DataRestaurante dr;
        Restaurante res= null;
        Producto prod = null;
        Map colProd = null;
        DataProducto dp;
        JTable tab = (JTable)evt.getSource();
        Point point = evt.getPoint();
        int fila = tab.rowAtPoint(point);
        if(evt.getClickCount() == 1){
            nomProd = jTabla.getValueAt(fila,0).toString();
            nick = jTabla.getValueAt(fila, 1).toString();
        }
        try{
            res = ICU.getRestauranteByNickname(nick);
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "El restaurante no está en el sistema","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        prod = res.getProducto(nomProd);
        //dp = prod.ProductoADP();
        
        VerInfoProd verinfop = new VerInfoProd(prod);
        verinfop.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jTablaMousePressed
//
//      try {
//           int fila = jTabla.getSelectedRow();
//           String dato = jTabla.getModel().getValueAt(fila, 0).toString();
//           JOptionPane.showMessageDialog(null, dato);
//           
//           
//       }catch(Exception e){
//           JOptionPane.showMessageDialog(null, "Error" +e.getMessage());
//       }
    
     private void cargarTabla(){
        Map Datas = new HashMap(); 
        Datas = ICU.listaDataRestaurantes();
        Iterator it = Datas.entrySet().iterator();
        String lista[]=new String[2];
        while(it.hasNext()){
            Map.Entry map = (Map.Entry) it.next();
            DataRestaurante dr = (DataRestaurante) map.getValue();
            //lista[0]=model.getSize()-1;
            lista[1]=dr.getNickname();
            Map colProd = dr.getColProducto();
            Iterator it2 = colProd.entrySet().iterator();
            while(it2.hasNext()){
                Map.Entry mapcol = (Map.Entry) it2.next();
                String nomProd = mapcol.getKey().toString();
                lista[0]=nomProd;
                modelo.insertRow((int)jTabla.getRowCount(), lista);
                
            }
                        
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
}
